INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Dog Harness', N'To put on the dog''s body.', N'Dog', CAST(34.99 AS Decimal(16, 2)), N'Leashes')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Canned Cat Food', N'Wet cat food.', N'Cat', CAST(18.90 AS Decimal(16, 2)), N'Food')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Flea & Tick', N'To prevent fleas and ticks.', N'Dog', CAST(30.00 AS Decimal(16, 2)), N'Medicine')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Crickets', N'Food for reptiles.', N'Lizard', CAST(18.99 AS Decimal(16, 2)), N'Food')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Cat Harness', N'To put in the cat''s body for a walk.', N'Cat', CAST(14.99 AS Decimal(16, 2)), N'Leashes')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Fish Flakes', N'Fish food.', N'Fish', CAST(13.95 AS Decimal(16, 2)), N'Food')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Ear Cleaner', N'Disinfectant for cleaning dog ears.', N'Dog', CAST(23.00 AS Decimal(16, 2)), N'Medicine')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'String Toy', N'Cat toy.', N'Cat', CAST(5.99 AS Decimal(16, 2)), N'Toys')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Kibbles', N'Dog kibble food.', N'Dog', CAST(42.99 AS Decimal(16, 2)), N'Food')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Chew Toy', N'Dog toy.', N'Dog', CAST(7.00 AS Decimal(16, 2)), N'Toys')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Terrarium', N'Reptile habitat.', N'Lizard', CAST(82.00 AS Decimal(16, 2)), N'Habitat')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Fish Tank', N'Tank for fish.', N'Fish', CAST(18.99 AS Decimal(16, 2)), N'Habitat')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Cat Treats', N'Treats for rewarding.', N'Cat', CAST(3.85 AS Decimal(16, 2)), N'Food')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Long Leash', N'For dog walking.', N'Dog', CAST(18.99 AS Decimal(16, 2)), N'Leashes')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Short Leash', N'For cat walking.', N'Cat', CAST(15.00 AS Decimal(16, 2)), N'Leashes')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Cat Tree', N'For cats to scratch and lay in.', N'Cat', CAST(65.00 AS Decimal(16, 2)), N'Habitat')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Dog Probiotics', N'Treates dog''s upset stomach.', N'Dog', CAST(32.00 AS Decimal(16, 2)), N'Medicine')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Cat Probiotics', N'Treats cat''s stomach issues.', N'Cat', CAST(28.95 AS Decimal(16, 2)), N'Medicine')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Reptile Probiotics', N'Treats reptile''s stomach issues.', N'Lizard', CAST(40.00 AS Decimal(16, 2)), N'Medicine')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Mouse Plushies', N'Toys for cats to play with.', N'Cat', CAST(5.99 AS Decimal(16, 2)), N'Toys')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Cat Collar', N'Collar for cats.', N'Cat', CAST(8.99 AS Decimal(16, 2)), N'Collars')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Dog Collar', N'Collar for dogs.', N'Dog', CAST(10.99 AS Decimal(16, 2)), N'Collars')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Terrarium Gravel', N'Gravel for reptile terrariums.', N'Lizard', CAST(17.85 AS Decimal(16, 2)), N'Habitat')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Cat Omega Vitamin', N'Vitamin supplement for cat health.', N'Cat', CAST(13.00 AS Decimal(16, 2)), N'Medicine')
INSERT INTO [dbo].[Products] ([ProductName], [Description], [Pet], [Price], [Category]) VALUES (N'Dog Omega Vitamin', N'Vitamin supplement for dogs health.', N'Dog', CAST(16.00 AS Decimal(16, 2)), N'Medicine')
